### PR TITLE
Add Bizimodu Baten Historia by Iskanbila

### PR DESCRIPTION
**Pull request by antaanimosity**

### CODE REVIEW

**Comment by snshn** [comment]
Thank you for this!  #984 just whitelisted "Basque" as a valid value for the Language metadata key, please feel free to rebase your commit against upstream, it's in `master`.

Seems like the files need a newline at the end, it's failing that test.

**Comment by antaanimosity** [comment]
Thanks, could you whitelist "Spanish" to? One of the songs it's in Spanish but the formatting was wrong and I think it didn't get detected (I'm fixing the format).

**Comment by snshn** [comment]
Please feel free to add it here https://github.com/Lyrics/lyrics-database/blob/master/tests/database-tests.d/4-metadata.py#L95
I don't want you have to rebase it again.

**Comment by snshn** [comment]
It's been merged and published on the website.  Thank you once again for the contribution.

**Pull request merged**
